#!/usr/bin/env bash
#
# dev-secrets.sh — generate backend/.env for local development from Bitwarden Secrets Manager.
#
# Pulls the shared application secrets from the same Bitwarden Secrets Manager project that CI
# uses (see .github/workflows/backend.yml) and writes a gitignored backend/.env. The backend
# already reads from the process environment (src/config.rs, via dotenvy + envy), so no code
# change is needed — this just removes the hand-edited .env step on a fresh clone.
#
# Per-developer values are NOT fetched from Bitwarden. Put them in backend/.env.local
# (gitignored); they are prepended verbatim so they win over the shared defaults:
#   SUPERADMIN_PASSWORD_HASH='<your argon2 hash>'   # required — generate with hash_password
#   DATABASE_URL=...                                # optional override
#   RUST_LOG=...                                    # optional override
#
# Usage:
#   export BWS_ACCESS_TOKEN=<your dev machine-account token>
#   ./scripts/dev-secrets.sh
#   cargo run
#
# Prerequisites:
#   - bws  (Bitwarden Secrets Manager CLI): https://bitwarden.com/help/secrets-manager-cli/
#   - jq
set -euo pipefail
umask 077  # secrets must never be group/world-readable, even transiently

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$BACKEND_DIR/.env"
LOCAL_FILE="$BACKEND_DIR/.env.local"

# Bitwarden region — EU vault, same as CI (.github/workflows/backend.yml). Override if needed.
export BWS_SERVER_URL="${BWS_SERVER_URL:-https://vault.bitwarden.eu}"

# Shared app-runtime secrets to pull from Bitwarden into .env.
# Deliberately EXCLUDES:
#   - SUPERADMIN_PASSWORD_HASH, DATABASE_URL : per-developer -> backend/.env.local
#   - LIGHTSAIL_*, GHCR_*, RCLONE_CONFIG     : deploy-only, not needed for local dev
SHARED_KEYS=(
  SECRET_KEY
  R2_ACCOUNT_ID
  R2_ACCESS_KEY_ID
  R2_SECRET_ACCESS_KEY
  INSTAGRAM_ACCESS_TOKEN_DEV
  INSTAGRAM_BUSINESS_ACCOUNT_ID_DEV
  INSTAGRAM_ACCESS_TOKEN_PROD
  INSTAGRAM_BUSINESS_ACCOUNT_ID_PROD
  FACEBOOK_APP_ID
  FACEBOOK_APP_SECRET
  OPENAI_API_KEY
  TELEGRAM_BOT_TOKEN
  TELEGRAM_ADMIN_CHAT_ID
  SOUNDCLOUD_CLIENT_ID
  SOUNDCLOUD_CLIENT_SECRET
  SOUNDCLOUD_ACCESS_TOKEN
  GITHUB_DISPATCH_TOKEN
)

die() { echo "error: $*" >&2; exit 1; }

command -v bws >/dev/null 2>&1 || die "bws (Bitwarden Secrets Manager CLI) is not installed.
  Install: https://bitwarden.com/help/secrets-manager-cli/ (e.g. 'cargo install bws' or a release binary)"
command -v jq >/dev/null 2>&1 || die "jq is not installed (e.g. 'brew install jq')."
[[ -n "${BWS_ACCESS_TOKEN:-}" ]] || die "BWS_ACCESS_TOKEN is not set.
  Create a dev machine-account access token in Bitwarden Secrets Manager, then:
    export BWS_ACCESS_TOKEN=<token>"

echo "Fetching secrets from Bitwarden ($BWS_SERVER_URL) ..." >&2
secrets_json="$(bws secret list --output json)" \
  || die "'bws secret list' failed — check BWS_ACCESS_TOKEN and BWS_SERVER_URL."
secrets_map="$(jq 'map({ (.key): .value }) | add // {}' <<<"$secrets_json")"

# Write atomically: build in a temp file on the same filesystem, then mv into place.
tmp="$(mktemp "$BACKEND_DIR/.env.tmp.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

missing=()
{
  echo "# GENERATED by backend/scripts/dev-secrets.sh from Bitwarden Secrets Manager."
  echo "# Do NOT edit by hand — re-run the script to refresh. Personal overrides go in .env.local."
  echo

  # 1) Per-developer overrides first. dotenvy keeps the FIRST definition of a duplicate key,
  #    so anything in .env.local wins over the shared values below.
  if [[ -f "$LOCAL_FILE" ]]; then
    echo "# --- from .env.local (per-developer overrides) ---"
    cat "$LOCAL_FILE"
    echo
  fi

  # 2) Shared secrets from Bitwarden, single-quoted so '$' (argon2, etc.) is never expanded.
  echo "# --- shared secrets (Bitwarden) ---"
  for key in "${SHARED_KEYS[@]}"; do
    val="$(jq -r --arg k "$key" '.[$k] // empty' <<<"$secrets_map")"
    if [[ -z "$val" ]]; then
      missing+=("$key")
      continue
    fi
    [[ "$val" == *"'"* ]] && die "secret $key contains a single quote — the .env single-quoted format can't represent it."
    printf "%s='%s'\n" "$key" "$val"
  done
  echo

  # 3) Non-secret local defaults (the app also has built-in defaults; pinned here for clarity).
  echo "# --- local non-secret defaults ---"
  cat <<'DEFAULTS'
R2_BUCKET_NAME=unheard-artists-dev
SOUNDCLOUD_REDIRECT_URI=http://localhost:8000/api/soundcloud/callback
GITHUB_REPO=phaabe/live.moafunk.de
RUST_LOG=info,tower_http=debug
DEFAULTS
} >"$tmp"

mv "$tmp" "$ENV_FILE"
trap - EXIT
chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE." >&2
(( ${#missing[@]} )) && echo "warning: not found in Bitwarden (left unset): ${missing[*]}" >&2

if [[ ! -f "$LOCAL_FILE" ]] || ! grep -q '^SUPERADMIN_PASSWORD_HASH=' "$LOCAL_FILE"; then
  cat >&2 <<'HINT'
note: SUPERADMIN_PASSWORD_HASH is not set in backend/.env.local — the backend needs it to start.
      1) cargo run --bin hash_password -- 'your-password'
      2) add to backend/.env.local (single-quoted):  SUPERADMIN_PASSWORD_HASH='<hash>'
HINT
fi
